apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: shuweic227/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
portForward:
  - resourceType: service
    resourceName: client-srv
    namespace: default  # Adjust if your service is in a different namespace
    port: 5173
    localPort: 5173  # The local port you want to forward to, can be the same or different